name: Check for New Release (CheckRelease-Clash.Verge.rev-installer)

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:     # 手动触发

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: 获取最新发布版本
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/clash-verge-rev/clash-verge-rev/releases/latest | jq -r '.tag_name')
          echo "latest_release=$latest_release" >> $GITHUB_ENV

      - name: 获取 Scoop 应用版本
        id: scoop_version
        run: |
          manifest_url="https://raw.githubusercontent.com/zhihaofans/Milk/main/bucket/Clash.Verge.rev-installer.json"
          scoop_version=$(curl -s $manifest_url | jq -r '.version')
          echo "scoop_version=$scoop_version" >> $GITHUB_ENV

      - name: 比较版本
        id: check_new_release
        run: |
          echo "GitHub Release 版本: $latest_release"
          echo "Scoop 版本: $scoop_version"
          
          if [ "$(printf '%s\n' "$latest_release" "$scoop_version" | sort -V | head -n1)" != "$latest_release" ]; then
            echo "检测到新版本: $latest_release"
            echo "is_new=true" >> $GITHUB_ENV
          else
            echo "Scoop 应用已是最新版本: $scoop_version"
            echo "is_new=false" >> $GITHUB_ENV
          fi

      - name: 执行操作
        if: env.is_new == 'true'
        run: |
          echo "检测到新发布，执行相应操作..."
          # 这里可以添加通知或自动更新 Scoop 清单的代码
