name: Check for New Release

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:     # 手动触发

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: 获取最新发布信息
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/clash-verge-rev/clash-verge-rev/releases/latest)
          latest_tag=$(echo "$latest_release" | jq -r .tag_name)
          echo "::set-output name=latest_tag::$latest_tag"

      - name: 检查是否为新发布
        id: check_new_release
        run: |
          echo "最新发布的标签是 ${{ steps.get_release.outputs.latest_tag }}"
          # 在此处添加您的逻辑，例如将最新标签与之前存储的标签进行比较

      # 在检测到新发布时执行的操作
      - name: 执行操作
        if: steps.check_new_release.outputs.is_new == 'true'
        run: |
          echo "检测到新发布，执行相应操作"
          # 在此处添加您的操作，例如发送通知或触发部署
